org: davidecavaliere
app: my-first-apigator
service: my-first-apigator # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2


plugins:
  - '@microgamma/serverless-apigator'

custom:
  apigator:
    entrypoint: handler
    buildFolder: build/main
    service: my-first.service

package:
  exclude:
    - ./*
    - ./**
    - '!build/**'
    - '!node_modules/**'
