org: davidecavaliere
app: my-first-apigator
service: my-first-apigator # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2


plugins:
  - '@microgamma/serverless-apigator'

custom:
  apigator:
    entrypoint: build/main/handler
    buildFolder: /home/davide/dev/my-first-apigator/build/main

package:
  exclude:
    - ./*
    - ./**
    - '!build/**'
    - '!node_modules/**'
